-- ABC Interiors certification project
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text not null,
  location text not null,
  property_type text not null,
  budget text not null,
  requirement text not null,
  message text,
  source text default 'website',
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;

-- For production, use a server-side endpoint/Edge Function with a service role
-- or create a narrowly scoped INSERT policy. Do not expose the service-role key
-- in browser code.
